### ISSUE TITLE
VRExpPluginExample could not be compiled. Try rebuilding from source manually.

### ISSUE THREAD

**Issue by ma4ukasan** [mordentral/VRExpPluginExample#11]
VRExpPluginExample could not be compiled. Try rebuilding from source manually. What should I do?
![Screenshot_534](https://user-images.githubusercontent.com/17165087/147663705-c3f19aa6-8b8a-446d-8001-7ab9a6a63a3b.png)
![Screenshot_535](https://user-images.githubusercontent.com/17165087/147663707-b8b80030-6273-46e5-8e32-2093b350035a.png)

**Comment by mordentral** [comment]
Build it from visual studio as per: https://vreue4.com/documentation?section=installation

Shipping binaries would be too large to store without a seperate LFS repo or something
