### ISSUE TITLE
UE5-Release: Couldn't find parent type for 'BucketUpdateSubsystem' named 'UTickableWorldSubsystem' in current module (Package: /Script/VRExpansionPlugin) or any other module parsed so far.

### ISSUE THREAD

**Issue by DabManTrips** [mordentral/VRExpPluginExample#13]
VRExpPluginExample-UE5-Release

Couldn't find parent type for 'BucketUpdateSubsystem' named 'UTickableWorldSubsystem' in current module (Package: /Script/VRExpansionPlugin) or any other module parsed so far.	VRExpPluginExample	D:\Unreal Projects\VRExpPluginExample-UE5-Release\Intermediate\ProjectFiles\EXEC	1

**Comment by mordentral** [comment]
I assume you were using the UE5 EA version? That subsystem type didn't exist back when that was branched off.
