### ISSUE TITLE
UE5-Release: "Attempting to release an actor with a null handle" error

### ISSUE THREAD

**Issue by GenioFallito** [mordentral/VRExpPluginExample#15]
After compile a fresh **UE5-Release** branch for **Unreal Engine 5 Preview 1**, in MotionControllerMap any grabbable objects I pick up behaves improperly.

In output log a yellow warning appear:

`LogChaos: Warning: Attempting to release an actor with a null handle`

Any ideas?

**Comment by mordentral** [comment]
Chaos in Preview1 is utterly broken, I have been told that the primary fix for it is slated for Preview 2.

The engines constraints and physics handle components have the same issues, the angular velocity application is incorrect.

**Comment by mordentral** [comment]
Also objects are going to sleep again when going to constrain them, which is a re-occuring issue with chaos that has been fixed twice now and keeps coming back.

**Comment by GenioFallito** [comment]
Understood. Thank you.
