### ISSUE TITLE
Unrecognized type 'TObjectPtr' - type must be a UCLASS, USTRUCT or UENUM	93	

### ISSUE THREAD

**Issue by zockerbube** [mordentral/VRExpPluginExample#16]
When trying to build the solution in order to open the example project I get the error message:

**Unrecognized type 'TObjectPtr' - type must be a UCLASS, USTRUCT or UENUM	93	**

I cannot build the project and have been unable to find the fix. Could anyone help out?

**Comment by mordentral** [comment]
You need to download the 4.27-Locked branch

Master is on UE5 now and that type only exists in UE5

**Comment by zockerbube** [comment]
Thank you so much!
