### ISSUE TITLE
Built in differnt version? 

### ISSUE THREAD

**Issue by Droyer0022** [mordentral/VRExpPluginExample#19]
Hello I downloaded the plugin and tried using the example pack but it keeps telling me to rebuild manually I am not really sure what to do!

**Comment by mordentral** [comment]
example doesn't come with pre-built binaries because they are too large for the repo. You have to compile it in visual studio

**Comment by chumchune** [comment]
I also encountered the same warning but, even if I try to compile it in Visual Studio, it still gives the same warning. Am I missing something?

**Comment by mordentral** [comment]
> I also encountered the same warning but, even if I try to compile it in Visual Studio, it still gives the same warning. Am I missing something?

Compile it for Development Editor config, that is what launching with the .uproject uses

**Comment by chumchune** [comment]
When I'm rebuilding it gives the errors of [The name "IncludeOrderVersion" does not exist in the current context.] and [The name "EngineIncludeOrderVersion" does not exist in the current context.]. I'm running out of ideas...

**Comment by mordentral** [comment]
> When I'm rebuilding it gives the errors of [The name "IncludeOrderVersion" does not exist in the current context.] and [The name "EngineIncludeOrderVersion" does not exist in the current context.]. I'm running out of ideas...

You are building the 5.1 engine version in an earlier engine version. IncludeOrderVersion was added in 5.1, you want to download the #-Locked branch that matches the engine version you are using.

**Comment by chumchune** [comment]
I checked everywhere to download the branch you mentioned but, I could not find it. Can you share the link of that webpage to download? If there is no webpage for it, I can also download the WinRaR zip, if you share.

**Comment by mordentral** [comment]
Its here, under the branch list, what engine version are you trying to use and i'll link it.

**Comment by chumchune** [comment]
OMG! I immediately and finally found it after you saying "Its here"!!! Thanks alot. Best VR developer <3
