### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Santhoshgdes** [mordentral/VRExpPluginExample#20]
![image](https://user-images.githubusercontent.com/99540185/195493322-63411664-9f99-43b9-a34b-9ff64bc558d5.png)
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unrecognized type 'TObjectPtr' - type must be a UCLASS, USTRUCT or UENUM	VRTest	D:\Softwares\UE_4.27\Engine\Plugins\VRExpansionPlugin-Master\VRExpansionPlugin\Source\VRExpansionPlugin\Public\VRBPDatatypes.h	130	
Error	MSB3073	The command "D:\Softwares\UE_4.27\Engine\Build\BatchFiles\Build.bat VRTestEditor Win64 Development -Project="D:\Paid\New folder (3)\VRExpPluginExample-master\VRTest.uproject" -WaitMutex -FromMsBuild" exited with code 6.	VRTest	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets	44

**Comment by mordentral** [comment]
you have a UE5 branch of the plugin and are trying to build it in an earlier engine version.
