### ISSUE TITLE
Empty

### ISSUE THREAD

**Issue by Santhoshgdes** [mordentral/VRExpPluginExample#21]
There is no files inside project completely Empty
![image](https://user-images.githubusercontent.com/99540185/195975179-f81f67fa-471f-4d3b-a174-94494cd7bdda.png)

**Comment by mordentral** [comment]
Map hasn't been changed in 5 months, i can assure you that it is fine, your download may have corrupted

**Comment by Santhoshgdes** [comment]
But inside all folders empty not only map

**Comment by wangandhao** [comment]
I had the same proplem, engine version 4.27.2

**Comment by mordentral** [comment]
Then re-download, your zip is corrupted

**Comment by issam1975** [comment]
do not download the zip file

but do a git clone
