### ISSUE TITLE
I developed using UE4.27, but I had an error using the template

### ISSUE THREAD

**Issue by xiongbaa** [mordentral/VRExpPluginExample#24]
Reconstruction has been chosen
The error is as follows
![屏幕截图 2023-03-11 101320](https://user-images.githubusercontent.com/92626757/224461179-85c88523-e1df-4d82-a66f-f6ae48336f7b.png)
![屏幕截图 2023-03-11 104918](https://user-images.githubusercontent.com/92626757/224461193-5c5806f0-6198-4f82-8d5b-ffe1c62be4be.png)
![屏幕截图 2023-03-11 104946](https://user-images.githubusercontent.com/92626757/224461195-e45b4ee1-bf5e-446a-915b-006d7ef7fedf.png)
![屏幕截图 2023-03-11 104955](https://user-images.githubusercontent.com/92626757/224461202-07a7c4f3-d306-49cc-91ac-de5a7f57d143.png)
![屏幕截图 2023-03-11 105013](https://user-images.githubusercontent.com/92626757/224461264-51b038a8-bb28-4573-8bf9-2c8495d78b7a.png)

**Comment by xiongbaa** [comment]
> 已选择重建 错误如下 ![屏幕截图 2023-03-11 101320](https://user-images.githubusercontent.com/92626757/224461179-85c88523-e1df-4d82-a66f-f6ae48336f7b.png) ![屏幕截图 2023-03-11 104918](https://user-images.githubusercontent.com/92626757/224461193-5c5806f0-6198-4f82-8d5b-ffe1c62be4be.png) ![屏幕截图 2023-03-11 104946](https://user-images.githubusercontent.com/92626757/224461195-e45b4ee1-bf5e-446a-915b-006d7ef7fedf.png) ![屏幕截图 2023-03-11 104955](https://user-images.githubusercontent.com/92626757/224461202-07a7c4f3-d306-49cc-91ac-de5a7f57d143.png)

![屏幕截图 2023-03-11 105013](https://user-images.githubusercontent.com/92626757/224461240-266209bd-c17a-43ce-bfde-cd8a4a0c9cdb.png)

**Comment by mordentral** [comment]
It looks like it is complaining about the directory you placed it in. Remove the engine version from the file path (4.27) and make sure the path name is within the standard 255 character limit.

**Comment by xiongbaa** [comment]
> 看起来它正在抱怨您放置它的目录。从文件路径 （4.27） 中删除引擎版本，并确保路径名在标准的 255 个字符限制内。

It is currently operating normally Thank you for your selfless dedication

**Comment by mordentral** [comment]
Good luck with your project and cheers
