### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by MaxStgs** [mordentral/VRExpPluginExample#25]
Hi, I found that example not working on Mac out of the box, I tried to repair by myself and looks like it works. My usecase is level design without specific VR development and I think it will usefull changes for some users.

Here is a guide on how this might work:
1) OpenVRExpansionPlugin.uplugin, need add Mac platform to "BlacklistPlatforms", code will looks like:
`{
    "Name": "OpenVRExpansionPlugin",
    "Type": "RunTime",
    "LoadingPhase": "Default",
    "BlacklistPlatforms": ["Mac"]
}`

2) Add file "MacEngine.ini" to Config/Mac with text, because "vr.InstancedStereo" looks like not supported on Mac.
`[/Script/Engine.RendererSettings]
vr.InstancedStereo=false`

3) Do anything with AdvancedSteamFriendsLibrary.cpp:411 (code around `UAdvancedSteamFriendsLibrary::FilterText` with `#if PLATFORM_MAC`)
May be need to check changes in AdvancedSteam plugin or remove Macros at all or initialize variable `FilterCount` by zero.

After these changes, the project compiled, opened and ran on the demo map without critical errors.

**Comment by JunjieXian** [comment]
I have to say, I love u
Its really helpfull

**Comment by mordentral** [comment]
Just disable those modules, they don't work on mac anyway.  Also the OpenVR expansion plugin is gone now in UE5 as openXR is the only viable path forward.

**Comment by MaxStgs** [comment]
My point (the topic of the issue) is that Mac users can't open the project at all, meaning they can't collaborate with other Windows/Linux users, and I think this should be fixed. Or will it work in branch 5.2? Maybe you see some correct way to do this?

**Comment by mordentral** [comment]
If they are using nodes from those modules in BP they will continue to not be able to open the project anyway if the platform is blacklisted as the module will not load.

For the advanced friends library I can fix that, the OpenVR module doesn't have a direct workaround though and it would be best to just disable it if the project is Mac compatible.

In 5.2 the openVR module is gone (deleted as it is deprecated now), so yes it would load (after the friends library change).

**Comment by mordentral** [comment]
@MaxStgs  I don't have a mac to cross compile and check the friends library with, do you have the full log output of it failing to compile there?

Mac was having problems with filter text so it was altered to use the old version for now. If it works with the newer function version now I have no way of knowing with out an output log.

Would prefer to try and keep the function working on Mac over just precompiling it out.

**Comment by MaxStgs** [comment]
1) > I don't have a mac to cross compile and check the friends library with, do you have the full log output of it failing to compile there?

```
[1/3] Compile Module.AdvancedSteamSessions.cpp
In file included from /Users/m.peters/Documents/code/VRExpPluginExample/Plugins/AdvancedSessions/AdvancedSteamSessions/Intermediate/Build/Mac/x86_64/UnrealEditor/Development/AdvancedSteamSessions/Module.AdvancedSteamSessions.cpp:7:
0>/Users/m.peters/Documents/code/VRExpPluginExample/Plugins/AdvancedSessions/AdvancedSteamSessions/Source/AdvancedSteamSessions/Private/AdvancedSteamFriendsLibrary.cpp:410:153: Error  : too few arguments to function call, expected 5, have 4
                        int FilterCount = SteamUtils()->FilterText(OutText, BufferLen, TCHAR_TO_ANSI(*TextToFilter), Context == EBPTextFilteringContext::FContext_GameContent);
```
                        
                        
2) > In 5.2 the openVR module is gone (deleted as it is deprecated now), so yes it would load (after the friends library change).

Problem is that OpenVR module is not available on Unreal Engine from Launcher (I didn't check from Source), there are not module at all.
Logs looks like
```
Invalidating makefile for VRExpPluginExampleEditor (OpenVRExpansionPlugin.uplugin modified)
/Applications/Xcode.app/Contents/Developer
Could not find definition for module 'OpenVR', (referenced via Target -> OpenVRExpansionPlugin.Build.cs)
```

What are you think about that all?

**Comment by mordentral** [comment]
I meant my OpenVRExpansion module is gone, and the reason the OpenVRExpansion module can't find the OpenVR module is because epic doesn't compile it against Mac (because it can't be, openVR doesn't support mac).

As for the sessions notice there, looks like the old function is removed entirely now, I will have to have mac also use the current function call.

**Comment by mordentral** [comment]
I just updated the sessions plugin to use the 5 parameter function call on Mac now, originally it had an exclusion to use the old one since the new one didn't function on Mac. I had comments in there to wait for Epic to fix it, guess they did.
