### ISSUE TITLE
UE 5.2 not able to build the project with VR plugin - code error UnrealArch 

### ISSUE THREAD

**Issue by ssshammi** [mordentral/VRExpPluginExample#26]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'UnrealArch' does not contain a definition for 'StartsWith' and no accessible extension method 'StartsWith' accepting a first argument of type 'UnrealArch' could be found (are you missing a using directive or an assembly reference?)	DefaultVR	C:\WORKING PROJECTS\Unreal Projects\Default XR Project\DefaultVR\Plugins\VRExpansionPlugin\OpenVRExpansionPlugin\Source\OpenVRExpansionPlugin\OpenVRExpansionPlugin.Build.cs	51	
should i just change it to x64 ? I would be building it for andriod quest 2 
<img width="1280" alt="image" src="https://github.com/mordentral/VRExpPluginExample/assets/2300969/6a5cb280-67f7-4d6b-82e6-529e86ddd255">

**Comment by ssshammi** [comment]
I commented the code 
Does nto work, so reverting back to 5.1 or 4.7

<img width="1100" alt="image" src="https://github.com/mordentral/VRExpPluginExample/assets/2300969/78edcf6a-73dd-423a-95cc-84347d4960e4">

**Comment by ssshammi** [comment]
Currently UE 5.2 is not supported.

**Comment by mordentral** [comment]
5.2 is supported, you need to download the Master branch. Master branch is always the latest version of the engine that is released and not in preview.
