### ISSUE TITLE
UE 4.27.2 Template Project has freezes in Quest 3 Launch

### ISSUE THREAD

**Issue by Rick86** [mordentral/VRExpPluginExample#28]
When I download the current UE 4.27.2 Template Project and launch it on my Quest 3, there are freezes every 2-3 seconds (you can cleary see them on the moving box). This is not the case with my older UE 4.27.2 Template Project and also not the case with the UE 5.3.2 template.
Not sure where I can find the version, the old (working) version has VRExpansionPlugin.uplugin creation date **2023-04-04** (downloaded maybe a month ago).
The latest (freezing) version has VRExpansionPlugin.uplugin creation date **2023-08-27**
I tried to copy the plugins from the working template to the freezing template, I can launch it but the freezes remain. So I'm pretty sure there is something wrong in the template.

BTW: Thank you very much for this awesome plugin! Great work, if I ever finish my VR project and earn some money, you will definetely get some too 😉.

**Comment by mordentral** [comment]
There isn't anything in the actual plugin itself that would/could cause that. The example template has some issues in one of the far corners on Quest 2 in 4.27, some weird engine bug with texture scaling. I am not aware of any other issues (though you should be turning off dynamic lighting if running on native).

**Comment by Rick86** [comment]
Mhh... I did not change anything in the templates, so I talk about the starting point (the center of the map).
I agree on you that there is no problem with the plugin itself (since replacing the plugin didn't help).
Any hints what you changed in the 4.27 template in the last 1-2 months that could cause this? I could use the old version, but maybe others will have the same problem.

**Comment by mordentral** [comment]
Nothing, there is nothing that changed in the template that could cause that
