### ISSUE TITLE
Trying to build VRExpansion plugin 5.2 is 

### ISSUE THREAD

**Issue by KarthikaGopala** [mordentral/VRExpPluginExample#29]
![SS](https://github.com/mordentral/VRExpPluginExample/assets/116074630/79027ddd-7a2e-4ec6-b94f-8c35c38f56a6)

Errors occured while buiding and it has failed.Suddenly gripping function not working and the error has occured [AttachTo would form cycle?]

**Comment by mordentral** [comment]
If you upgraded from an earlier version to 5 then you need to change up how the grasping hands attachment proxy works due to engine changes. The new example changed it up so that they are default in the character now instead of live spawned.
