### ISSUE TITLE
Moving assets to different folder

### ISSUE THREAD

**Issue by Tokusei** [mordentral/VRExpPluginExample#3]
hey, I tried to move all the asset data for the example project into its own folder in the content browser. After fixing up redirectors, a lot of the assets still fail to load in the VRExpPluginExample map. Seems like there are some hard references to some of the assets, is there some way to fix this?

**Comment by mordentral** [comment]
Some of the blueprints will need recompiled / reset, the vivepawnchar and the grasping hands for example reference each other.

**Comment by Tokusei** [comment]
Hi, I rebuilt the blueprints and it seems like they are working as expected, the weird thing is that the example map will bug out when I move it into another folder. A bunch of actors in the scene are deleted and there are empty references once I reload it after moving

![EH2](https://user-images.githubusercontent.com/4631534/104832023-f3af7d80-58c8-11eb-8899-a6f5a551e223.png)
