### ISSUE TITLE
Getting out of the car and adding a Discord.

### ISSUE THREAD

**Issue by EddieSoloProjects** [mordentral/VRExpPluginExample#34]
First I have to say this really needs a proper Discord. Would love the ability to discuss with other users of this plugin. Second when playing the example I sometimes get sucked into the backseat of the car. And I can't figure out how to leave it.

**Comment by mordentral** [comment]
The website directly links to the discord....

And the car uses the same buttons on the outside to get out, since its an example i never bothered to add interior ones.
