### ISSUE TITLE
5.3 locked branch - HandSocketComponent.cpp ESkinCacheUsage::Disabled undefined

### ISSUE THREAD

**Issue by give-me-pen** [mordentral/VRExpPluginExample#36]
It seems the latest commit to 5.3 locked is causing these compilation errors for me:

Grippables\HandSocketComponent.cpp(784): error C2027: use of undefined type 'ESkinCacheUsage'

Grippables\HandSocketComponent.cpp(784): error C2065: 'Disabled': undeclared identifier

**Comment by mordentral** [comment]
I forgot to port a fix from the primary repo to the example, it should be fine now.
