### ISSUE TITLE
Cannot compile/build | Git clone cannot find 4.26 repository

### ISSUE THREAD

**Issue by jessekirbs** [mordentral/VRExpPluginExample#7]
I've followed the installation instructions to install 4.26 branch but I am experiencing build issues. When I download master or 4.26-Locked branch from Github, I select my Unreal version (4.26) and it successfully generates the project files. When I try to open the Unreal project, it asks if I'd like to rebuild and I select yes - it starts to compile/build and then says it failed and to try building from source. 

When I try to clone the 4.26-Locked branch from command line, I get the following:

`Cloning into '4.26-Locked'...
fatal: repository 'https://github.com/mordentral/VRExpPluginExample/tree/4.26-Locked/' not found`

I've made sure to install .NET dependencies for Visual Studio.

Any suggestions for how to get the 4.26 template working? Thank you!

**Comment by mordentral** [comment]
You have to compile it in visual studio from the project files it generates, launching into ue4 doesn’t compile plugin modules

**Comment by mordentral** [comment]
also you don't use the top address to clone, use the clone buttons address

https://github.com/mordentral/VRExpPluginExample.git

**Comment by zmifsx** [comment]
Hello, visual studio 2019 compile failed with ue4 4.26 using cloned master branch
Do I need the 4-26_locked branch instead?

**Comment by mordentral** [comment]
yes, master branch is always latest current release of the engine (currently 4.27)

**Comment by zmifsx** [comment]
Build successful, but now the editor stuck at initializing... 45%. What to do now?
Nevermind, that's because I copied the plugins wrong

**Comment by mordentral** [comment]
stuck at 45% is normal for the engine anyway, its when it generates the data cache, you just don't see it on BP only projects.

**Comment by jessekirbs** [comment]
Thanks so much, @mordentral. Stupid mistakes on my part. Thanks for the assistance!
