### ISSUE TITLE
undefined symbol: ___aeabi_unwind_cpp_pr1

### ISSUE THREAD

**Issue by zmifsx** [mordentral/VRExpPluginExample#9]
Blank project packages fine for Quest 2 Mobile Android
But this happens if I try to do the same for the example project. Perhaps I missed something crucial?
![errrorr](https://user-images.githubusercontent.com/58888818/135591009-35eeab2e-f716-47a2-b268-97a6075b8d7c.PNG)

Build log file:
[UBT-VRExpPluginExample-Android-Development.txt](https://github.com/mordentral/VRExpPluginExample/files/7265778/UBT-VRExpPluginExample-Android-Development.txt)

**Comment by mordentral** [comment]
Blank project isn't a c++ project, you need to install the correct android NDK in order to compile for android, I believe that quest2 requires minimum SDK version 25 if I remember correctly, due to a thermal sensor function it uses.

**Comment by zmifsx** [comment]
> 
> 
> Blank project isn't a c++ project, you need to install the correct android NDK in order to compile for android, I believe that quest2 requires minimum SDK version 25 if I remember correctly, due to a thermal sensor function it uses.

Thank you! My SDK 29 is correct, but I got the wrong NDK & JDK
